"use client";
import "./globals.css";
import { lightTheme } from "../theme/themes";
import { ThemeProvider, CssBaseline } from "@mui/material";
import Head from "next/head";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import { RecoilRoot } from "recoil";
import { AppProgressBar as ProgressBar } from 'next-nprogress-bar';
import { QueryClientProvider, QueryClient } from "@tanstack/react-query";

const queryClient = new QueryClient();

export default function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang="en">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet" />
      </Head>
      <ThemeProvider theme={lightTheme}>
        <CssBaseline />
        <RecoilRoot>
        <QueryClientProvider client={queryClient}>
          <body>
            <ToastContainer/>
            {children}
            <ProgressBar 
              height="4px"
              color="#051390"
              options={{ showSpinner: false }}
              shallowRouting
              />
          </body>
        </QueryClientProvider>
        </RecoilRoot>
      </ThemeProvider>
    </html>
  );
}